# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8b46780747e00d1ff8d60a70d9ecd8380a338563c201881f16d20627648b0fee19a697586286a9cc16fc7d23c08a83987663f509bde692df3e1a42aac15d908

test:
  secret_key_base: 4d9e844cdb341ffdfcc20c224470d2a08f25346c8037b1726f3ce83723c4c02fe4b8d0e8db6faeea986544f4dee482f46ee5eb02862ccc7636879535ec95a497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
